### ISSUE TITLE
空调数量

### ISSUE THREAD

**Issue by MrQQQQQQQQQQ** [idreamshen/esphome-uart-vrf#1]

**Comment by MrQQQQQQQQQQ** [comment]
按教程接好线，esphome web 端显示出了 32台内机，实际上 只有三台内机。  使用 中弘和 PTX的 网关都试过 ，都是一样的显示。并且 在使用中弘网关时，从web 端的日志看 仍然走的 德姆瑞的 协议。

**Comment by idreamshen** [comment]
1. 提供下 web 端日志
2. vrf 网关液晶屏的内机和协议拍照看下（液晶屏可以翻页）

**Comment by MrQQQQQQQQQQ** [comment]
<img width="1396" alt="Pasted Graphic" src="https://github.com/user-attachments/assets/1b6f968e-1e95-4f6c-ab36-118ac99ce3db">
![WX20241012-222205@2x](https://github.com/user-attachments/assets/2af56a65-1866-400a-8ad2-bd5283c70b5b)
![WX20241012-222227@2x](https://github.com/user-attachments/assets/70b9eecf-e4bd-4a15-afb7-01228a683995)

**Comment by idreamshen** [comment]
1. 中弘 vrf 与 esp 的接线拍照
2. 中弘 vrf 插网线连接电脑，然后访问中弘 vrf 的 web 控制台，截图 485 的设置页面

**Comment by MrQQQQQQQQQQ** [comment]
<img width="609" alt="Pasted Graphic 1" src="https://github.com/user-attachments/assets/4732e3e4-373a-4a53-93ca-516eac0fe323">

<img width="575" alt="Pasted Graphic 2" src="https://github.com/user-attachments/assets/4c843589-acee-4f07-9068-3ebcb11d9a0f">

**Comment by idreamshen** [comment]
1. VRF 上的 485 是 RS485 A1/B1 这两个端子，不是 BUS A/B 端子。
2. 中弘 485 端子默认通信好像是有校验，可以通过其 web 控制台关闭。或者在 esphome yaml 中修改 uart.parity 的值。

**Comment by MrQQQQQQQQQQ** [comment]
哦，明白了，可能就是这里的问题。我再试下。中弘 485 端子默认通校验 我关闭了。

**Comment by MrQQQQQQQQQQ** [comment]
<img width="844" alt="image" src="https://github.com/user-attachments/assets/972b92b9-96b6-4eca-9bf1-3c21a6b0a433">

**Comment by idreamshen** [comment]
改成 A1、B1 试试呢

**Comment by MrQQQQQQQQQQ** [comment]
esphome:
  name: esp-vrf-zhonghong
  friendly_name: esp-vrf-zhonghong

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: ""
  password: ""

captive_portal:


logger:
  baud_rate: 0

external_components:
  - source:
      type: git
      url: https://github.com/idreamshen/esphome-uart-vrf
    refresh: 5min

# 启用Web服务器，允许通过HTTP进行设备控制
web_server:
  port: 80

  
uart:
  - id: myuart1
    tx_pin: 1
    rx_pin: 3
    baud_rate: 9600

uart_vrf:

climate:

**Comment by MrQQQQQQQQQQ** [comment]
似乎还是一样，日志仍然是 之前那种

**Comment by MrQQQQQQQQQQ** [comment]
更奇怪的是， 我现在不接A和B,  esphome 这边 日志都在输出

**Comment by idreamshen** [comment]
看你图上 YZ_RS485_V1 这块板子，没有供电输入？它需要 3.3/5v + GND 的电源接入

**Comment by MrQQQQQQQQQQ** [comment]
我之前发现不接 供电也打日志，所以就没接供电。我再接供电 试试

**Comment by idreamshen** [comment]
485 转 uart 需要供电，否则转换芯片会不起作用

**Comment by MrQQQQQQQQQQ** [comment]
不行，接了供电，也没有区别

**Comment by MrQQQQQQQQQQ** [comment]
为啥 我即使不接入 vrf 的a,b ，也有日志输出呢

**Comment by MrQQQQQQQQQQ** [comment]
<img width="762" alt="image" src="https://github.com/user-attachments/assets/f3e4d843-910c-4fba-8cc3-6b09bc654306">
这里显示A1,B1 是新风  ，这个有关系吗？

**Comment by MrQQQQQQQQQQ** [comment]
重新接一遍线后，日志变成这样了。 
[23:19:53][C][logger:185]: Logger:
[23:19:53][C][logger:186]:   Level: DEBUG
[23:19:53][C][logger:188]:   Log Baud Rate: 0
[23:19:53][C][logger:189]:   Hardware UART: UART0
[23:19:53][C][uart.arduino_esp8266:118]: UART Bus:
[23:19:53][C][uart.arduino_esp8266:119]:   TX Pin: GPIO1
[23:19:53][C][uart.arduino_esp8266:120]:   RX Pin: GPIO3
[23:19:53][C][uart.arduino_esp8266:122]:   RX Buffer Size: 256
[23:19:53][C][uart.arduino_esp8266:124]:   Baud Rate: 9600 baud
[23:19:53][C][uart.arduino_esp8266:125]:   Data Bits: 8
[23:19:53][C][uart.arduino_esp8266:126]:   Parity: NONE
[23:19:53][C][uart.arduino_esp8266:127]:   Stop bits: 1
[23:19:53][C][uart.arduino_esp8266:129]:   Using hardware serial interface.
[23:19:53][C][captive_portal:088]: Captive Portal:
[23:19:53][C][web_server:145]: Web Server:
[23:19:53][C][web_server:146]:   Address: esp-vrf-zhonghong.local:80
[23:19:53][C][mdns:116]: mDNS:
[23:19:53][C][mdns:117]:   Hostname: esp-vrf-zhonghong
[23:19:53][C][esphome.ota:073]: Over-The-Air updates:
[23:19:53][C][esphome.ota:074]:   Address: esp-vrf-zhonghong.local:8266
[23:19:53][C][esphome.ota:075]:   Version: 2
[23:19:53][C][esphome.ota:078]:   Password configured
[23:19:53][C][safe_mode:018]: Safe Mode:
[23:19:53][C][safe_mode:019]:   Boot considered successful after 60 seconds
[23:19:53][C][safe_mode:021]:   Invoke after 10 boot attempts
[23:19:53][C][safe_mode:022]:   Remain in safe mode for 300 seconds
[23:19:53][C][api:139]: API Server:
[23:19:53][C][api:140]:   Address: esp-vrf-zhonghong.local:6053
[23:19:53][C][api:142]:   Using noise encryption: YES
[23:19:53][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:19:58][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:03][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:08][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:13][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:18][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:23][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:24][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[23:20:28][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:33][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:38][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:43][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:48][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:20:53][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:20:58][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:21:03][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:21:08][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
[23:21:13][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10)
[23:21:18][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)

esphome 的web 端一台机器也没有了。

**Comment by idreamshen** [comment]
> 重新接一遍线后，日志变成这样了。 [23:19:53][C][logger:185]: Logger: [23:19:53][C][logger:186]: Level: DEBUG [23:19:53][C][logger:188]: Log Baud Rate: 0 [23:19:53][C][logger:189]: Hardware UART: UART0 [23:19:53][C][uart.arduino_esp8266:118]: UART Bus: [23:19:53][C][uart.arduino_esp8266:119]: TX Pin: GPIO1 [23:19:53][C][uart.arduino_esp8266:120]: RX Pin: GPIO3 [23:19:53][C][uart.arduino_esp8266:122]: RX Buffer Size: 256 [23:19:53][C][uart.arduino_esp8266:124]: Baud Rate: 9600 baud [23:19:53][C][uart.arduino_esp8266:125]: Data Bits: 8 [23:19:53][C][uart.arduino_esp8266:126]: Parity: NONE [23:19:53][C][uart.arduino_esp8266:127]: Stop bits: 1 [23:19:53][C][uart.arduino_esp8266:129]: Using hardware serial interface. [23:19:53][C][captive_portal:088]: Captive Portal: [23:19:53][C][web_server:145]: Web Server: [23:19:53][C][web_server:146]: Address: esp-vrf-zhonghong.local:80 [23:19:53][C][mdns:116]: mDNS: [23:19:53][C][mdns:117]: Hostname: esp-vrf-zhonghong [23:19:53][C][esphome.ota:073]: Over-The-Air updates: [23:19:53][C][esphome.ota:074]: Address: esp-vrf-zhonghong.local:8266 [23:19:53][C][esphome.ota:075]: Version: 2 [23:19:53][C][esphome.ota:078]: Password configured [23:19:53][C][safe_mode:018]: Safe Mode: [23:19:53][C][safe_mode:019]: Boot considered successful after 60 seconds [23:19:53][C][safe_mode:021]: Invoke after 10 boot attempts [23:19:53][C][safe_mode:022]: Remain in safe mode for 300 seconds [23:19:53][C][api:139]: API Server: [23:19:53][C][api:140]: Address: esp-vrf-zhonghong.local:6053 [23:19:53][C][api:142]: Using noise encryption: YES [23:19:53][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:19:58][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:03][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:08][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:13][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:18][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:23][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:24][I][safe_mode:041]: Boot seems successful; resetting boot loop counter [23:20:28][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:33][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:38][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:43][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:48][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:20:53][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:20:58][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:21:03][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:21:08][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7) [23:21:13][D][uart_vrf:223]: uart send 01.AA.FF.FF.FF.FF.FF.FF.FF.A4 (10) [23:21:18][D][uart_vrf:223]: uart send 01.50.02.FF.FF.FF.50 (7)
> 
> esphome 的web 端一台机器也没有了。

这是在满足以下条件的日志输出吗？
1. 485转接板接中弘 vrf 的 BUS A/B 端子
2. 485转接板供电

**Comment by idreamshen** [comment]
> 为啥 我即使不接入 vrf 的a,b ，也有日志输出呢

1. 如果看到的日志都是 `uart send`，那符合预期
2. 如果看到 `uart send` `uart receive` 交替日志，那不符合预期，需要检查 485 转接板是否有问题

**Comment by MrQQQQQQQQQQ** [comment]
<img width="201" alt="image" src="https://github.com/user-attachments/assets/777f295e-2274-4382-b867-95fd35f1bf2a">
是的，现在接的是 这里 A1,B1. 看到的都是 uart send 日志。但是 web 端一台机器没有显示。 
空调应该只需要是接通电源就可以了吧，不需要每台内机 都是开启的状态吧？

**Comment by idreamshen** [comment]
> <img alt="image" width="201" src="https://private-user-images.githubusercontent.com/8612380/376091686-777f295e-2274-4382-b867-95fd35f1bf2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzI5NjEsIm5iZiI6MTcyODg3MjY2MSwicGF0aCI6Ii84NjEyMzgwLzM3NjA5MTY4Ni03NzdmMjk1ZS0yMjc0LTQzODItYjg2Ny05NWZkMzVmMWJmMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTRUMDIyNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQxNzViNDJjM2NjYTcyMmI5NDA5MGZjMjE1NzhjMTk3MWJmYTJjZjhjNjQ3YzY1YWRkYWEzOGQ1ZDE0MTI4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1z6yWieGJ5rhIU0SsL1h2knwFNEPOVnfbFKG6jIg190"> 是的，现在接的是 这里 A1,B1. 看到的都是 uart send 日志。但是 web 端一台机器没有显示。 空调应该只需要是接通电源就可以了吧，不需要每台内机 都是开启的状态吧？

1. 改成接 BUS A/B 端子（因为根据你提供的 vrf web 控制台的截图，AB 对应空调）
2. 空调内机不需要启动，空调内机接通电源即可

再观察下 esphome 日志

**Comment by MrQQQQQQQQQQ** [comment]
<img width="761" alt="image" src="https://github.com/user-attachments/assets/44ea1c9c-ebb8-4056-99f5-ead1e5bf3f36">
web 端 这里说的 智能 A,B. 新风 A1,B1.  所以有点 疑惑 是应该 接 rs485这里的A1,B1 还是 bus 这里的 A,B.   中弘 web 端 这里 新风 A1,B1 的 波特率 是 4800 且 无法修改。

**Comment by MrQQQQQQQQQQ** [comment]
我 在ha 论坛看教程帖子里也是用的这款中弘 vrf，看外观 应该是同一个型号，web 端rs485 通讯参数这里 应该也是一样的有 A,B.    A1,B1.  A2,B2的设置吧。  还一种可能就是 这款 vrf 在扫码 远程升级时 选的升级配置不同？

**Comment by MrQQQQQQQQQQ** [comment]
重新接 vrf bus 这时的 A,B 后。 日志输出如下：

20:51:56 | [D] | [uart_vrf:223] | uart send 01.19.FF.FF.FF.FF.FF.FF.FF.13 (10)
-- | -- | -- | --
20:51:57 | [D] | [uart_vrf:223] | uart send 01.1A.FF.FF.FF.FF.FF.FF.FF.14 (10)
20:51:58 | [D] | [uart_vrf:223] | uart send 01.1B.FF.FF.FF.FF.FF.FF.FF.15 (10)
20:51:59 | [D] | [uart_vrf:223] | uart send 01.1C.FF.FF.FF.FF.FF.FF.FF.16 (10)
20:52:00 | [D] | [uart_vrf:223] | uart send 01.1D.FF.FF.FF.FF.FF.FF.FF.17 (10)
20:52:01 | [D] | [uart_vrf:223] | uart send 01.1E.FF.FF.FF.FF.FF.FF.FF.18 (10)
20:52:02 | [D] | [uart_vrf:223] | uart send 01.1F.FF.FF.FF.FF.FF.FF.FF.19 (10)
20:52:03 | [D] | [uart_vrf:223] | uart send 01.10.FF.FF.FF.FF.FF.FF.FF.0A (10)
20:52:04 | [D] | [uart_vrf:223] | uart send 01.11.FF.FF.FF.FF.FF.FF.FF.0B (10)
20:52:05 | [D] | [uart_vrf:223] | uart send 01.12.FF.FF.FF.FF.FF.FF.FF.0C (10)
20:52:06 | [D] | [uart_vrf:223] | uart send 01.13.FF.FF.FF.FF.FF.FF.FF.0D (10)
20:52:07 | [D] | [uart_vrf:223] | uart send 01.14.FF.FF.FF.FF.FF.FF.FF.0E (10)
20:52:08 | [D] | [uart_vrf:223] | uart send 01.15.FF.FF.FF.FF.FF.FF.FF.0F (10)
20:52:09 | [D] | [uart_vrf:223] | uart send 01.16.FF.FF.FF.FF.FF.FF.FF.10 (10)
20:52:10 | [D] | [uart_vrf:223] | uart send 01.17.FF.FF.FF.FF.FF.FF.FF.11 (10)
20:52:11 | [D] | [uart_vrf:223] | uart send 01.08.FF.FF.FF.FF.FF.FF.FF.02 (10)
20:52:12 | [D] | [uart_vrf:223] | uart send 01.09.FF.FF.FF.FF.FF.FF.FF.03 (10)
20:52:13 | [D] | [uart_vrf:223] | uart send 01.0A.FF.FF.FF.FF.FF.FF.FF.04 (10)
20:52:14 | [D] | [uart_vrf:223] | uart send 01.0B.FF.FF.FF.FF.FF.FF.FF.05 (10)
20:52:15 | [D] | [uart_vrf:223] | uart send 01.0C.FF.FF.FF.FF.FF.FF.FF.06 (10)
20:52:16 | [D] | [uart_vrf:223] | uart send 01.0D.FF.FF.FF.FF.FF.FF.FF.07 (10)
20:52:17 | [D] | [uart_vrf:223] | uart send 01.0E.FF.FF.FF.FF.FF.FF.FF.08 (10)
20:52:18 | [D] | [uart_vrf:223] | uart send 01.0F.FF.FF.FF.FF.FF.FF.FF.09 (10)
20:52:19 | [D] | [uart_vrf:223] | uart send 01.00.FF.FF.FF.FF.FF.FF.FF.FA (10)
20:52:20 | [D] | [uart_vrf:223] | uart send 01.01.FF.FF.FF.FF.FF.FF.FF.FB (10)
20:52:21 | [D] | [uart_vrf:223] | uart send 01.02.FF.FF.FF.FF.FF.FF.FF.FC (10)
20:52:22 | [D] | [uart_vrf:223] | uart send 01.03.FF.FF.FF.FF.FF.FF.FF.FD (10)
20:52:23 | [D] | [uart_vrf:223] | uart send 01.04.FF.FF.FF.FF.FF.FF.FF.FE (10)
20:52:24 | [D] | [uart_vrf:223] | uart send 01.05.FF.FF.FF.FF.FF.FF.FF.FF (10)
20:52:25 | [D] | [uart_vrf:223] | uart send 01.06.FF.FF.FF.FF.FF.FF.FF.00 (10)
20:52:26 | [D] | [uart_vrf:223] | uart send 01.07.FF.FF.FF.FF.FF.FF.FF.01 (10)
20:52:27 | [D] | [uart_vrf:223] | uart send 01.18.FF.FF.FF.FF.FF.FF.FF.12 (10)
20:52:28 | [D] | [uart_vrf:223] | uart send 01.19.FF.FF.FF.FF.FF.FF.FF.13 (10)
20:52:29 | [D] | [uart_vrf:223] | uart send 01.1A.FF.FF.FF.FF.FF.FF.FF.14 (10)
20:52:30 | [D] | [uart_vrf:223] | uart send 01.1B.FF.FF.FF.FF.FF.FF.FF.


并且出来了 32台内机。

**Comment by MrQQQQQQQQQQ** [comment]
<img width="1363" alt="未命名_副本" src="https://github.com/user-attachments/assets/304bbae8-4721-4a25-9614-9d1adb6a7278">

**Comment by MrQQQQQQQQQQ** [comment]
<img width="1429" alt="截屏2024-10-14 21 55 38" src="https://github.com/user-attachments/assets/c76a8877-a2f8-4e11-ba71-39bfa8e43afa">
刚刚接好线后放着一段时间没动，现在 左边的机器又没了。日志仍然在输出

**Comment by idreamshen** [comment]
> <img alt="截屏2024-10-14 21 55 38" width="1429" src="https://private-user-images.githubusercontent.com/8612380/376269274-c76a8877-a2f8-4e11-ba71-39bfa8e43afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTgxMzEsIm5iZiI6MTcyODk1NzgzMSwicGF0aCI6Ii84NjEyMzgwLzM3NjI2OTI3NC1jNzZhODg3Ny1hMmY4LTRlMTEtYmE3MS0zOWJmYThlNDNhZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDIwMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMyYWEwN2JkMzIwMWYyN2ViYTFhY2IzOTgxNTQ4NjFhYjI4NDI2YWE1MzU4MjllYjY3YjcyNDY5NWM5YWNlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.K3ROAQQeefRY54FC-5DWz-mtosP_wf5_khBWOO94lZI"> 刚刚接好线后放着一段时间没动，现在 左边的机器又没了。日志仍然在输出

可以尝试手动用 usb-ttl 和 vrf 485 端子通信确认数据包是否正确。
向“中弘 vrf”发送 `01 50 02 FF FF FF 50` 该数据包，并检查返回值

**Comment by MrQQQQQQQQQQ** [comment]
> > <img alt="截屏2024-10-14 21 55 38" width="1429" src="https://private-user-images.githubusercontent.com/8612380/376269274-c76a8877-a2f8-4e11-ba71-39bfa8e43afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTgxMzEsIm5iZiI6MTcyODk1NzgzMSwicGF0aCI6Ii84NjEyMzgwLzM3NjI2OTI3NC1jNzZhODg3Ny1hMmY4LTRlMTEtYmE3MS0zOWJmYThlNDNhZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMDIwMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDMyYWEwN2JkMzIwMWYyN2ViYTFhY2IzOTgxNTQ4NjFhYjI4NDI2YWE1MzU4MjllYjY3YjcyNDY5NWM5YWNlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.K3ROAQQeefRY54FC-5DWz-mtosP_wf5_khBWOO94lZI"> 刚刚接好线后放着一段时间没动，现在 左边的机器又没了。日志仍然在输出
> 
> 可以尝试手动用 usb-ttl 和 vrf 485 端子通信确认数据包是否正确。 向“中弘 vrf”发送 `01 50 02 FF FF FF 50` 该数据包，并检查返回值

应该是  usb-ttl  接 rs485转 ttl板子吧？ 接上线按 9600， 8n1 连接， 结果无法连接上，没有任何输出。 测了下 vrf 的 A,B 两个端子间 是有 大概 1.5v 的电压差。

**Comment by idreamshen** [comment]
1. 检查“rs485 转 ttl”板子是否有异常。可以尝试如下这款。
![image](https://github.com/user-attachments/assets/e400f761-4617-448e-a10b-ac276f9f31fa)
2. 也有可能 vrf 自身阉割了 485 端子的输出，试试拆机能否找到原始的 uart 串口

**Comment by MrQQQQQQQQQQ** [comment]
> 1. 检查“rs485 转 ttl”板子是否有异常。可以尝试如下这款。
>    ![image](https://private-user-images.githubusercontent.com/7069142/376863122-e400f761-4617-448e-a10b-ac276f9f31fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDU3NDUsIm5iZiI6MTcyOTA0NTQ0NSwicGF0aCI6Ii83MDY5MTQyLzM3Njg2MzEyMi1lNDAwZjc2MS00NjE3LTQ0OGUtYTEwYi1hYzI3NmY5ZjMxZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDIyNDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE1NGFmYTE5ODhjMTNmZDQzYWE1MDc4YTE4MmQ1NzgzNDM3YWI1NmVkMmZiN2RjOGUzZThhOTE3Y2YyOGQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JBfpYk6ApkytfBXBIxreO1cFjrMbQV-7bQkpff0RNp0)
> 2. 也有可能 vrf 自身阉割了 485 端子的输出，试试拆机能否找到原始的 uart 串口

上图这个版型的 板子我也买了一个，效果一样（当然也不排除 是我焊接接线端子的时候把板子弄坏了，这种可能性不大）。
晚上回去把vrf 拆开看看。
